version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  apexai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apexai
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - apexai-data:/home/apexai/apex_auto_project
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=codellama:instruct
      - MAX_CYCLES=7
      - LOG_LEVEL=INFO
    depends_on:
      ollama:
        condition: service_healthy
    command: ["gui"]

volumes:
  ollama-data:
  apexai-data:

