version: 2.1
orbs:
  python: circleci/python@2
  evals: circleci/evals@2.0
jobs:
  test-python:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Run tests
          command: pytest --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')
      - store_test_results:
          path: junit.xml
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: "#e.g. ./deploy.sh"
  evals-test-assertions-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - evals/test:
          assertions: assertions.json
          metrics: eval_results.json
          results: test_results.xml
  ios-build:
    macos:
      xcode: "15.3.0"
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler
      - run:
          name: Install Fastlane
          command: bundle install || gem install fastlane
      - run:
          name: Fastlane Build
          command: bundle exec fastlane build || fastlane build
      - store_artifacts:
          path: build
workflows:
  build-and-test:
    jobs:
      - test-python:
          context:
            - OpenAI-context
  test-eval-workflow:
    jobs:
      - evals-test-assertions-job
  ios-build-workflow:
    jobs:
      - ios-build